version: '3.8'

services:
  web:
    build: .
    ports:
      - "5005:5005"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=mysql+pymysql://aimuspal:password123@db:3306/aimuspal_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      - JWT_SECRET_KEY=your-jwt-secret-key-change-in-production
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./app:/app/app
      - ./static:/app/static
      - ./aimuspal_homepage.html:/app/aimuspal_homepage.html
      - ./aimuspal_homepage_formatted.html:/app/aimuspal_homepage_formatted.html
      - ./aimuspal_new_homepage.html:/app/aimuspal_new_homepage.html
      - ./config.py:/app/config.py
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=aimuspal_db
      - MYSQL_USER=aimuspal
      - MYSQL_PASSWORD=password123
      - MYSQL_ROOT_PASSWORD=rootpassword123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql_data:
  redis_data: