"""Initial database migration

Revision ID: 79f7d6a43337
Revises: 
Create Date: 2025-07-16 03:58:16.850384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f7d6a43337'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('suggestions', sa.Text(), nullable=True))
        batch_op.drop_column('improvement_suggestions')
        batch_op.drop_column('ai_feedback')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_feedback', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('improvement_suggestions', sa.TEXT(), nullable=True))
        batch_op.drop_column('suggestions')
        batch_op.drop_column('feedback')
        batch_op.drop_column('audio_file_path')

    # ### end Alembic commands ###
